# Generated by Django 5.2.7 on 2025-11-05 13:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applicant_name", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "monthly_income",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "declared_debts",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("country", models.CharField(max_length=5)),
                ("loan_purpose", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("NEEDS_REVIEW", "Needs Review"),
                        ],
                        default="NEEDS_REVIEW",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pipeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PipelineRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "final_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("NEEDS_REVIEW", "Needs Review"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline_runs",
                        to="loans.application",
                    ),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="loans.pipeline",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Pipeline Runs",
            },
        ),
        migrations.CreateModel(
            name="StepLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_type", models.CharField(max_length=50)),
                ("outcome", models.CharField(max_length=50)),
                ("detail", models.JSONField(default=dict)),
                (
                    "execution_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "pipeline_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_logs",
                        to="loans.pipelinerun",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Step Logs",
                "ordering": ["execution_time"],
            },
        ),
        migrations.CreateModel(
            name="PipelineStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step_type",
                    models.CharField(
                        help_text="store the class name (e.g., 'dti_rule', 'risk_scoring')",
                        max_length=50,
                    ),
                ),
                ("order", models.IntegerField()),
                ("params", models.JSONField(default=dict)),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="loans.pipeline",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Pipeline Steps",
                "ordering": ["order"],
                "unique_together": {("pipeline", "order")},
            },
        ),
        migrations.CreateModel(
            name="TerminalRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "condition",
                    models.CharField(
                        help_text="The condition is a string expression to be evaluated, (e.g., dti_rule.outcome == 'FAIL')",
                        max_length=255,
                    ),
                ),
                (
                    "final_status",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("NEEDS_REVIEW", "Needs Review"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terminal_rules",
                        to="loans.pipeline",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Terminal Rules",
                "ordering": ["order"],
                "unique_together": {("pipeline", "order")},
            },
        ),
    ]
